DEVICES = [
    {
        "class": "Medical",
        "device_id": "7f47ccf9-582d-42b8-88bd-052a1d236839",
        "type": "Infusion Pump",
        "location": "Satellite Clinic",
        "model": "Alaris GW Volumetric Pump",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "00e12926-fb84-4f62-a81b-1077dafc6ada",
        "type": "Anesthesia Machine",
        "location": "Main Campus",
        "model": "GE Datex Ohmeda Avance S5 Anesthesia Machine",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d36e5022-c739-4c5a-95a2-d304e1cf8aea",
        "type": "Workstation",
        "location": "Underground Lair",
        "model": "GE CIC Pro",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "ff2647da-c553-43ed-a7ca-8567a4819ae1",
        "type": "Angiography Workstation",
        "location": "Main Campus",
        "model": "Siemens Artis Cockpit",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "cd081db3-e243-46f4-9635-3fa8d8321de4",
        "type": "Blood Analyzer",
        "location": "Underground Lair",
        "model": "Abbott i-STAT Handheld",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "8c253c1a-c21f-44da-85c4-9e22e2111d92",
        "type": "Blood Analyzer",
        "location": "Satellite Clinic",
        "model": "Abbott i-STAT Handheld",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "7cd99006-d561-4a5a-9f26-87d0fec05add",
        "type": "Barcode Printer",
        "location": "Main Campus",
        "model": "DH Technology Barcode Printer",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "798f05f1-d85d-40b5-be5d-45edf4d5cf18",
        "type": "Security Camera",
        "location": "Main Campus",
        "model": "AXIS M3046-V",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "f88098c1-e47e-4bae-a542-4aecddf22e62",
        "type": "Barcode Printer",
        "location": "Main Campus",
        "model": "DH Technology Barcode Printer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "25bb84c5-09d8-48ce-9833-40f25135c375",
        "type": "Infusion Gateway",
        "location": "Main Campus",
        "model": "Alaris Gateway Workstation",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "46a195e7-2924-497e-af87-0cd3c03f1e61",
        "type": "Smart TV",
        "location": "Satellite Clinic",
        "model": "Samsung J5202 LED TV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "edfc250b-d927-4974-9a6a-ef5ff4c4663c",
        "type": "Anesthesia Machine",
        "location": "Satellite Clinic",
        "model": "GE Datex Ohmeda Avance S5 Anesthesia Machine",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "04987f68-d406-487d-bbdc-92ca7c5178d3",
        "type": "Imaging Printer",
        "location": "Underground Lair",
        "model": "Ricoh MPC2003SP Printer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "e1feb958-210a-4e41-8c06-22d0ceaa3f9c",
        "type": "Angiography Workstation",
        "location": "Underground Lair",
        "model": "Siemens Artis Cockpit",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "6bc53680-a246-48d9-bccf-2a1f3541df04",
        "type": "Security Camera",
        "location": "Underground Lair",
        "model": "AXIS M3046-V",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "a2581077-ad7f-4289-9189-daacbc53b1bb",
        "type": "Blood Analyzer",
        "location": "Main Campus",
        "model": "Abbott i-STAT Handheld",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "0aa370cc-e6e4-4fdd-a401-bf9954137fa0",
        "type": "Anesthesia Machine",
        "location": "Main Campus",
        "model": "GE Datex Ohmeda Avance S5 Anesthesia Machine",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "5dc7d49e-febf-431f-9f9c-47b73ba1d13f",
        "type": "Printer",
        "location": "Underground Lair",
        "model": "Brother MFC-L2750DW Printer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "0f8a4eaa-8e5f-48d8-ba58-d24fe81c9428",
        "type": "Electrolyte Analyzer",
        "location": "Satellite Clinic",
        "model": "Roche Diagnostics AVL 9180",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "8a934487-26dc-456e-b545-c494d828b2b2",
        "type": "Printer",
        "location": "Satellite Clinic",
        "model": "Brother MFC-L2750DW Printer",
        "organization": "NYU",
    },
    {
        "class": "Infrastructure",
        "device_id": "e361f54d-bf60-46bf-be64-51040b835383",
        "type": "Environment Monitor",
        "location": "Underground Lair",
        "model": "NetBotz Wireless Sensor Pod 180",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "4b96bc0b-ab45-45b7-b81b-2aecff075f9b",
        "type": "Blood Analyzer",
        "location": "Underground Lair",
        "model": "Abbott i-STAT Handheld",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "6a767f9a-20e3-42e1-a7a2-49b6c2c3ba94",
        "type": "Barcode Printer",
        "location": "Satellite Clinic",
        "model": "DH Technology Barcode Printer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "85b40852-c8b2-4f8e-a30e-7a510ace465a",
        "type": "Angiography Machine",
        "location": "Underground Lair",
        "model": "Siemens Artis Zee",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "5e67d6d9-3473-469f-a744-53e16a0260e5",
        "type": "Imaging Workstation",
        "location": "Satellite Clinic",
        "model": "GE Centricity Viewer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "7d3fb33b-61df-434f-a918-fd3d37962d4e",
        "type": "Electrolyte Analyzer",
        "location": "Satellite Clinic",
        "model": "Roche Diagnostics AVL 9180",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "8aafbfca-ef06-4e09-8771-126320cb475c",
        "type": "Anesthesia Machine",
        "location": "Underground Lair",
        "model": "GE Datex Ohmeda Avance S5 Anesthesia Machine",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d75c54d3-e672-4580-8bd1-b39ea9c66e93",
        "type": "Electrolyte Analyzer",
        "location": "Underground Lair",
        "model": "Roche Diagnostics AVL 9180",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "c2df92e3-7cac-478a-9c35-11efd20c9a27",
        "type": "Ultrasound",
        "location": "Main Campus",
        "model": "GE Vivid S6",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "3880e491-fbb6-46c8-905e-63160d1405c0",
        "type": "Angiography Workstation",
        "location": "Main Campus",
        "model": "Siemens Artis Cockpit",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "c244613c-443b-4dbc-b278-747d982d6f84",
        "type": "Infusion Pump",
        "location": "Main Campus",
        "model": "Alaris GW Volumetric Pump",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "92da93a9-1816-4d1c-9276-e7262048863d",
        "type": "Angiography Machine",
        "location": "Main Campus",
        "model": "Siemens Artis Zee",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "8124b480-6e91-4f01-9c33-50c66e2e71a8",
        "type": "Smart TV",
        "location": "Satellite Clinic",
        "model": "Samsung J5202 LED TV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d884da0b-ce10-4ece-b258-28efdbaeca08",
        "type": "Angiography Workstation",
        "location": "Satellite Clinic",
        "model": "Siemens Artis Cockpit",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "fe57c7e9-ddec-4b64-9294-881c07a1b112",
        "type": "Infusion Gateway",
        "location": "Main Campus",
        "model": "Alaris Gateway Workstation",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "cf4844bc-a107-4e0a-84e1-fa04d76d388c",
        "type": "Electrolyte Analyzer",
        "location": "Underground Lair",
        "model": "Roche Diagnostics AVL 9180",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "ba3e3493-866e-4ebd-ac71-0629f0fa0737",
        "type": "Angiography Workstation",
        "location": "Main Campus",
        "model": "Siemens Artis Cockpit",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "b79e1e4c-674b-4bbb-a6ce-5f9fcb110afc",
        "type": "Smart TV",
        "location": "Underground Lair",
        "model": "Samsung J5202 LED TV",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "e90b26f7-e545-4009-a8f2-71263498919b",
        "type": "Security Camera",
        "location": "Main Campus",
        "model": "AXIS M3046-V",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "6073da8a-22cb-450e-83a6-c665dfafff31",
        "type": "Blood Analyzer",
        "location": "Satellite Clinic",
        "model": "Abbott i-STAT Handheld",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "6a58ed21-2311-4149-b1b8-6fb82655cb14",
        "type": "Barcode Printer",
        "location": "Underground Lair",
        "model": "DH Technology Barcode Printer",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "786b2b79-047a-4f48-9224-f05cae59a453",
        "type": "Security Camera",
        "location": "Underground Lair",
        "model": "AXIS M3046-V",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "af5bee0a-d5e4-4ce1-82bf-f685da42c2c7",
        "type": "Infusion Pump",
        "location": "Underground Lair",
        "model": "Alaris GW Volumetric Pump",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d1e7bd57-40b6-409c-bc95-e1b7793b0e0d",
        "type": "Angiography Machine",
        "location": "Satellite Clinic",
        "model": "Siemens Artis Zee",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "a5ca19e0-95e2-4b41-bd2b-80b7c59bd1f8",
        "type": "Smart TV",
        "location": "Satellite Clinic",
        "model": "Samsung J5202 LED TV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "6af4b6c0-845b-4f98-823c-fd6691d8d873",
        "type": "Imaging Printer",
        "location": "Main Campus",
        "model": "Ricoh MPC2003SP Printer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "39dcd6e8-a8bc-4bf9-ac7e-15bf0917ee46",
        "type": "Anesthesia Machine",
        "location": "Satellite Clinic",
        "model": "GE Datex Ohmeda Avance S5 Anesthesia Machine",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "adc967b4-192d-4b20-a3a5-a1e7397cd29c",
        "type": "CT Machine",
        "location": "Satellite Clinic",
        "model": "GE Revolution Evo",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "71d6c3a3-ddb5-47e5-9765-bc63d4bffa12",
        "type": "Security Camera",
        "location": "Main Campus",
        "model": "AXIS M3046-V",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "48ffaf68-5ffe-4720-8366-d9385a3832be",
        "type": "Workstation",
        "location": "Satellite Clinic",
        "model": "GE CIC Pro",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "a93c3983-58ce-4b65-a7b3-4c6260081e28",
        "type": "Electrolyte Analyzer",
        "location": "Main Campus",
        "model": "Roche Diagnostics AVL 9180",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d81985f6-7371-4b1f-a4d8-428eae177d38",
        "type": "DNA Amplification System",
        "location": "Satellite Clinic",
        "model": "GeneXpert IV",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "553aa534-5138-4cad-a611-962bef5f69d1",
        "type": "Security Camera",
        "location": "Satellite Clinic",
        "model": "AXIS M3046-V",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "e2564bd5-0deb-4dce-92a1-843282960ae2",
        "type": "Imaging Workstation",
        "location": "Underground Lair",
        "model": "GE Centricity Viewer",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "6a2b00ef-ba03-49f6-9f6e-965a1219702d",
        "type": "Printer",
        "location": "Underground Lair",
        "model": "Brother MFC-L2750DW Printer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "f3b21a8f-e11b-4494-8615-2f524f98b64d",
        "type": "Angiography Machine",
        "location": "Satellite Clinic",
        "model": "Siemens Artis Zee",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "f2327d7b-6804-429e-80e6-3b93aa41acc3",
        "type": "DNA Amplification System",
        "location": "Satellite Clinic",
        "model": "GeneXpert IV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "9908b266-133b-4015-8ef1-f5d42221b7a6",
        "type": "Angiography Workstation",
        "location": "Main Campus",
        "model": "Siemens Artis Cockpit",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "3ff2c859-5664-4d13-9e7f-4cb6f64ed281",
        "type": "Blood Analyzer",
        "location": "Satellite Clinic",
        "model": "Abbott i-STAT Handheld",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d416ff1b-0af7-4868-b038-38e691283dfa",
        "type": "Imaging Printer",
        "location": "Main Campus",
        "model": "Ricoh MPC2003SP Printer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "e02e4eed-1ec6-45c6-994b-76e613c5da09",
        "type": "DNA Amplification System",
        "location": "Underground Lair",
        "model": "GeneXpert IV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d417190e-7413-4d8b-acc4-51f6924c43ec",
        "type": "Electrolyte Analyzer",
        "location": "Main Campus",
        "model": "Roche Diagnostics AVL 9180",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "69639c99-dea4-4c2d-8bb2-412145fada65",
        "type": "Imaging Workstation",
        "location": "Main Campus",
        "model": "GE Centricity Viewer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "9dec70ab-99ba-41ff-912d-8d3c6c76a3d2",
        "type": "Blood Analyzer",
        "location": "Satellite Clinic",
        "model": "Abbott i-STAT Handheld",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "4517f44a-726a-4a08-852a-9cf9f4706b51",
        "type": "Infusion Pump",
        "location": "Main Campus",
        "model": "Alaris GW Volumetric Pump",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "a440aa5e-88f5-41fd-9c8a-69254c7cb93d",
        "type": "Smart TV",
        "location": "Main Campus",
        "model": "Samsung J5202 LED TV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "80c6371d-2d39-4bad-b7fc-0af3a5e1bbb0",
        "type": "DNA Amplification System",
        "location": "Underground Lair",
        "model": "GeneXpert IV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "0a781675-ec01-4340-979e-13dea54578d6",
        "type": "Imaging Workstation",
        "location": "Main Campus",
        "model": "GE Centricity Viewer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d33ee064-ae82-459d-8b0b-225098ff5ee9",
        "type": "CT Machine",
        "location": "Satellite Clinic",
        "model": "GE Revolution Evo",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "a93dda1f-7a6d-4240-99b3-b64c5fbee747",
        "type": "Ultrasound",
        "location": "Main Campus",
        "model": "GE Vivid S6",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "d5a19a62-d3e1-4cce-b1c4-b52bad32b7ef",
        "type": "Smart TV",
        "location": "Main Campus",
        "model": "Samsung J5202 LED TV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "8ba3949e-cf4a-4f47-9097-4a81ea21dc32",
        "type": "Anesthesia Machine",
        "location": "Main Campus",
        "model": "GE Datex Ohmeda Avance S5 Anesthesia Machine",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "61e6a605-74ce-4af9-9a65-8fd8e7f5679a",
        "type": "Anesthesia Machine",
        "location": "Satellite Clinic",
        "model": "GE Datex Ohmeda Avance S5 Anesthesia Machine",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "2b50346c-0128-4dcd-b719-f9d6798bebf8",
        "type": "Imaging Workstation",
        "location": "Underground Lair",
        "model": "GE Centricity Viewer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "47dee7a1-0837-41d1-8fbb-2c2055d09f01",
        "type": "Infusion Gateway",
        "location": "Satellite Clinic",
        "model": "Alaris Gateway Workstation",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "b29a8ccc-6653-46f0-93fb-4bd484b5643e",
        "type": "Integration System",
        "location": "Main Campus",
        "model": "BD Pyxis MedStation",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "179048b2-ac01-4f6f-88a6-7c2c47cb1304",
        "type": "DNA Amplification System",
        "location": "Main Campus",
        "model": "GeneXpert IV",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "886085c0-713c-4166-8a5f-206211f15780",
        "type": "Smart TV",
        "location": "Satellite Clinic",
        "model": "Samsung J5202 LED TV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "47cf5dc7-5981-4382-b9c5-f81f354340e4",
        "type": "Imaging Printer",
        "location": "Underground Lair",
        "model": "Ricoh MPC2003SP Printer",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "f716f40f-ec5b-49c0-8e32-87088de1a982",
        "type": "Smart TV",
        "location": "Main Campus",
        "model": "Samsung J5202 LED TV",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "741c36ef-f2fa-471a-8d5f-ce12b34bbec6",
        "type": "Smart TV",
        "location": "Satellite Clinic",
        "model": "Samsung J5202 LED TV",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "4e7d2fa7-2291-4dbc-8754-ffe121cb6f92",
        "type": "Angiography Workstation",
        "location": "Main Campus",
        "model": "Siemens Artis Cockpit",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "41d07e7d-ad37-4eef-b407-252b2bab1868",
        "type": "Infusion Gateway",
        "location": "Satellite Clinic",
        "model": "Alaris Gateway Workstation",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d2c7cedc-0a76-4bda-9c0b-c20bb62e715a",
        "type": "Angiography Workstation",
        "location": "Satellite Clinic",
        "model": "Siemens Artis Cockpit",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "893adb80-2655-427a-bbe1-5e2ee6c65bca",
        "type": "Angiography Workstation",
        "location": "Satellite Clinic",
        "model": "Siemens Artis Cockpit",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "6288e560-7e23-44dd-8db9-52f289cc5394",
        "type": "Barcode Printer",
        "location": "Main Campus",
        "model": "DH Technology Barcode Printer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "7c518334-2a43-4b82-9e92-d6e3049049d5",
        "type": "Ultrasound",
        "location": "Underground Lair",
        "model": "GE Vivid S6",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "7f2e0c35-d720-4b9c-a016-60879fb4db8d",
        "type": "Infusion Gateway",
        "location": "Satellite Clinic",
        "model": "Alaris Gateway Workstation",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "4cc852b8-a3f4-4cd2-9a8a-0198a4ecd998",
        "type": "Infusion Gateway",
        "location": "Underground Lair",
        "model": "Alaris Gateway Workstation",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "300911e1-09de-430e-ae27-68a9aa3cd9b5",
        "type": "Integration System",
        "location": "Underground Lair",
        "model": "BD Pyxis MedStation",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "d8086d53-eee2-495f-88c5-4623c99b735d",
        "type": "Blood Analyzer",
        "location": "Satellite Clinic",
        "model": "Abbott i-STAT Handheld",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "c3ce10fa-191e-44bf-9f33-d219ebddab42",
        "type": "Imaging Printer",
        "location": "Satellite Clinic",
        "model": "Ricoh MPC2003SP Printer",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "1cd09ca9-ee8c-4a38-ae7f-b6e4d422b4be",
        "type": "Imaging Workstation",
        "location": "Underground Lair",
        "model": "GE Centricity Viewer",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "bd2b4a7a-d1c4-4799-b690-f8a69a2c64ab",
        "type": "Printer",
        "location": "Main Campus",
        "model": "Brother MFC-L2750DW Printer",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "04827402-0725-437c-bc22-c9670ea084f0",
        "type": "Printer",
        "location": "Satellite Clinic",
        "model": "Brother MFC-L2750DW Printer",
        "organization": "NYU",
    },
    {
        "class": "Misc IoT",
        "device_id": "6287768c-ea5a-4699-9dce-e0fbe1d4944c",
        "type": "Security Camera",
        "location": "Main Campus",
        "model": "AXIS M3046-V",
        "organization": "NYU",
    },
    {
        "class": "Infrastructure",
        "device_id": "12efa4cd-af40-4d4f-8fac-92204551c3ae",
        "type": "Environment Monitor",
        "location": "Main Campus",
        "model": "NetBotz Wireless Sensor Pod 180",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "35cc5dab-3d43-4e3b-aeab-78a87a92dcba",
        "type": "Integration System",
        "location": "Main Campus",
        "model": "BD Pyxis MedStation",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "29b88f8c-14e0-4873-bfd1-40f49c5eb2d8",
        "type": "Blood Analyzer",
        "location": "Satellite Clinic",
        "model": "Abbott i-STAT Handheld",
        "organization": "NYU",
    },
    {
        "class": "Medical",
        "device_id": "c8f14396-dfc2-4269-a098-6d998c1c287f",
        "type": "Infusion Gateway",
        "location": "Satellite Clinic",
        "model": "Alaris Gateway Workstation",
        "organization": "NYU",
    },
]
